name: Pipeline Sistema Bancario

on:
  push:
    branches: [ "master", "main", "desarrollo" ]
  pull_request:
    branches: [ "master", "main", "desarrollo" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Descargar Codigo de C#
      uses: actions/checkout@v4

    - name: 2. Configurar Entorno MSBuild (Herramientas de Windows)
      uses: microsoft/setup-msbuild@v2

    - name: 3. Configurar Gestor de Paquetes NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: 4. Restaurar Dependencias de la Solucion
      run: nuget restore SistemaBancario.sln

    - name: 5. Compilar Solucion de Formularios y Clases
      run: msbuild SistemaBancario.sln /p:Configuration=Debug

    - name: 6. Ejecutar Pruebas Unitarias Automatizadas
      run: msbuild SistemaBancario.sln /t:VSTest /p:Configuration=Debug
