name: Pipeline Sistema Bancario

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Descargar Codigo de C#
      uses: actions/checkout@v4

    - name: 2. Configurar Entorno MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: 3. Configurar Gestor de Paquetes NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: 4. Restaurar Paquetes NuGet de la Solucion
      run: nuget restore
      shell: powershell

    - name: 5. Instalar Motor de Pruebas via NuGet
      run: nuget install Microsoft.TestPlatform -Version 17.8.0 -OutputDirectory Packages_Test

    - name: 6. Compilar Proyectos de la Solucion
      run: msbuild /t:Clean,Build /p:Configuration=Debug
      shell: powershell

    - name: 7. Ejecutar Pruebas Automatizadas
      run: |
        $vstestPath = Get-ChildItem -Path "Packages_Test" -Filter "vstest.console.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        $targetDll = Get-ChildItem -Filter "*Test*.dll" -Recurse | Where-Object { $_.FullName -like "*bin\Debug*" } | Select-Object -First 1 -ExpandProperty FullName
        if ($targetDll) {
            Write-Host "Ejecutando pruebas sobre: $targetDll"
            & $vstestPath "$targetDll"
        } else {
            Write-Error "¡Error Critico! No se encontro la DLL del proyecto de pruebas en bin\Debug."
            exit 1
        }
      shell: powershell
